#pragma once

const unsigned int WINDOW_WIDTH = 990;
const unsigned int WINDOW_HEIGHT = 770;
const int TEXT_SIZE = 18;
const int BUTTON_WIDTH = 250;
const int BUTTON_HEIGHT = 60; 
const int INTERVAL_BETWEEN_BUTTONS = 70;
const int START_POS_X_VIEW_BUTTONS = 50;
const int START_POS_Y_VIEW_BUTTONS = 30;
const int POS_X_DEPARTMENTS_VIEW_BUTTON = START_POS_X_VIEW_BUTTONS;
const int POS_Y_DEPARTMENTS_VIEW_BUTTON = START_POS_Y_VIEW_BUTTONS; 
const int POS_X_COUNTERPARTIES_VIEW_BUTTON = START_POS_X_VIEW_BUTTONS;
const int POS_Y_COUNTERPARTIES_VIEW_BUTTON = POS_Y_DEPARTMENTS_VIEW_BUTTON + INTERVAL_BETWEEN_BUTTONS; 
const int POS_X_EMPLOYEES_VIEW_BUTTON = START_POS_X_VIEW_BUTTONS;
const int POS_Y_EMPLOYEES_VIEW_BUTTON = POS_Y_COUNTERPARTIES_VIEW_BUTTON + INTERVAL_BETWEEN_BUTTONS; 
const int POS_X_APPLICATIONS_VIEW_BUTTON = START_POS_X_VIEW_BUTTONS;
const int POS_Y_APPLICATIONS_VIEW_BUTTON = POS_Y_EMPLOYEES_VIEW_BUTTON + INTERVAL_BETWEEN_BUTTONS; 
const int POS_X_REPAIR_OF_NODES_VIEW_BUTTON = START_POS_X_VIEW_BUTTONS;
const int POS_Y_REPAIR_OF_NODES_VIEW_BUTTON = POS_Y_APPLICATIONS_VIEW_BUTTON + INTERVAL_BETWEEN_BUTTONS; 
const int POS_X_SIMPLE_REPAIR_VIEW_BUTTON = START_POS_X_VIEW_BUTTONS;
const int POS_Y_SIMPLE_REPAIR_VIEW_BUTTON = POS_Y_REPAIR_OF_NODES_VIEW_BUTTON + INTERVAL_BETWEEN_BUTTONS;
const int POS_X_COMPLEX_REPAIR_VIEW_BUTTON = START_POS_X_VIEW_BUTTONS;
const int POS_Y_COMPLEX_REPAIR_VIEW_BUTTON = POS_Y_SIMPLE_REPAIR_VIEW_BUTTON + INTERVAL_BETWEEN_BUTTONS; 
const int POS_X_EARNINGS_OF_EMPLOYEES_VIEW_BUTTON = START_POS_X_VIEW_BUTTONS;
const int POS_Y_EARNINGS_OF_EMPLOYEES_VIEW_BUTTON = POS_Y_COMPLEX_REPAIR_VIEW_BUTTON + INTERVAL_BETWEEN_BUTTONS;

const int BUTTON_WIDTH_BOTTOM_PANEL = 200;
const int BUTTON_HEIGHT_BOTTOM_PANEL = 40;
const int INTERVAL_BETWEEN_BUTTONS_BOTTOM_PANEL = 50;

const int START_POS_X_BUTTONS_OF_BOTTOM_PANEL = 750;
const int START_POS_Y_BUTTONS_OF_BOTTOM_PANEL = 600;

const int POS_X_EDIT_BUTTON = START_POS_X_BUTTONS_OF_BOTTOM_PANEL;
const int POS_Y_EDIT_BUTTON = START_POS_Y_BUTTONS_OF_BOTTOM_PANEL;
const int POS_X_ACCEPT_BUTTON = POS_X_EDIT_BUTTON;
const int POS_Y_ACCEPT_BUTTON = POS_Y_EDIT_BUTTON + INTERVAL_BETWEEN_BUTTONS_BOTTOM_PANEL;
const int POS_X_EXIT_BUTTON = POS_X_EDIT_BUTTON;
const int POS_Y_EXIT_BUTTON = POS_Y_ACCEPT_BUTTON + INTERVAL_BETWEEN_BUTTONS_BOTTOM_PANEL;

const int POS_X_OUTPUT_WINDOW = 340;
const int POS_Y_OUTPUT_WINDOW = 30;
const int OUTPUT_WINDOW_WIDTH = 600;
const int OUTPUT_WINDOW_HEIGHT = 550;

const int POS_X_ADD_BUTTON = 330;
const int POS_Y_ADD_BUTTON = 600;
const int POS_X_REMOVE_BUTTON = 540;
const int POS_Y_REMOVE_BUTTON = 600;
